### ISSUE TITLE
Parameters for cyclic carbonates 

### ISSUE THREAD

**Issue by mdelsa** [paduagroup/fftool#10]
Hi, I was trying to simulate some carbonates, specifically propylene carbonate and ethylene carbonate and other not cyclic, but I can't find the parameters in the force field so that the molecules are neutral. The cyclic residuals with the respective parameters used among those present in the force field are:

      O_2                 O_2
      ||                  ||
      C_2               C_2
     /   \               /   \
    OS   OS     OS   OS
     \   /               \   /
     CT-CT        CT-CT
             \           
              CT
propylencarbonate     ethylencarbonate

Thank you for your time.

**Comment by agiliopadua** [comment]
I've added parameters for CT in EC and PC from OPLS-AA to the file oplsaa.ff
