### ISSUE TITLE
output to Amber

### ISSUE THREAD

**Issue by weilaigit** [paduagroup/fftool#12]
Is there a way for fftool to output to Amber?  I tried to output to GROMACS first and then used Parmed to convert GROMACS topology to Amber but got the error that it couldn't identify the file format.

**Comment by agiliopadua** [comment]
Unfortunately I don't use AMBER and am not really familiar with its file formats. I don't use gromacs that much either, so this output format is not maintained very actively, unless someone reports an issue. Writing the code for a new output format should not be very complicated if you know the format well.
