### ISSUE TITLE
Units conversion: GROMACS to LAMMPS

### ISSUE THREAD

**Issue by matteo-northvolt** [paduagroup/fftool#8]
Good morning,

I am having some issue in understanding the units conversion from the GROMACS .itp file into the LAMMPS .ff one. Please correct me if I am wrong. 
GROMACS adopts the following units:

`sigma [nm]   epsilon [kJ/mol]   b_0 [nm]   k_b [kJ mol-1 nm-2]`

whereas LAMMPS, when `units real` key is used, has the following units:

`sigma [Å]   epsilon [kcal/mol]   b_0 [Å]   k_b [kcal mol-1 Å-2]`

 To give you an example the .itp file is like:

`[ atomtypes ] opls_800  C800    12.0110     0.000    A    3.50000E-01   2.76144E-01`, where `[ atoms ]      1   opls_800      1    UNK   C00      1    -0.0487    12.0110`

Whereas .ff looks like:

`ATOMS C00   C00    12.011  -0.0487   lj    3.50   0.27614`

Here I see the conversion from nm to Å, but I don't see the conversion from kJ/mol to kcal/mol. I am quite sure that here I am missing something, but I don't what I am missing.

Furthermore the equation used by [GROMACS](https://manual.gromacs.org/current/reference-manual/functions/bonded-interactions.html) to define the bonded interaction uses a 1/2 term as prefactor, whereas the one used by [LAMMPS](https://docs.lammps.org/bond_harmonic.html), when the `bond_style harmonic` key is used, don't. Which means that all the k_b terms should be divided by 200 (if we don't consider the kJ to kcal conversion) when converting from GROMACS ([kJ mol-1 nm-2]) to LAMMPS real units ([kcal mol-1 Å-2]). Whereas I get:

GROMACS .itp
`[ bonds ]                                                                                                                                                                                                     2     1     1      0.1410 267776.000`

LAMMPS .ff
`BONDS                                                                                                                                                                                                     O01 C00  harm   1.410   2677.8 `

I am probably missing something since the simulations I run give reasonable results, but I just wanted to be sure about why especially since I need to write a customized .ff file by hand and I don't want to use erroneous values/units.

Thanks.

  Matteo

**Comment by agiliopadua** [comment]
Hi,
Units are usually a mess...
The parameters in the fftool force field file (*.ff) are converted into lammps, gromacs, etc. input files.
For Lennard-Jones fftool uses kJ and A, LAMMPS kcal and A, Gromacs kJ and nm.
For harmonic bonds and angles fftool uses k/2, LAMMPS uses K, Gromacs k/2. 
Did you find a mistake in the input files created using fftool?
Best,
Agilio

**Comment by matteo-northvolt** [comment]
Dear Agilio,

I just noticed that the script I used to create the .ff is not from fftool, but it is indeed from another repository. This is what happen when you wrap all in one bash script. Sorry for the inconvenience!

Best,

  Matteo
