### ISSUE TITLE
pdb files for systems with more than 99999 atoms

### ISSUE THREAD

**Issue by ssmirella** [paduagroup/fftool#9]
Hello all,

I have generated input files for OpenMM using fftool and my system contains more than 100000 atoms. When running OpenMM I get an error "ValueError: Misaligned residue name" and it points to the line of atom 100000. 
The error is solved by manually removing one space from the front of the residue name for all residues after 99999. 
Is it possible to include this on the code?

Thank you!

**Comment by kateryna-goloviznina** [comment]
Example from Mirella's mail:

"HETATM99999 H25  ole"
6:11 corresponds to "99999 "
12:16 to "H25  "
17:20 to "ole"

"HETATM100000 C15  ole"
6:11 to "100000"
12:16 to " C15 "
17:20 to " ol"

Actually, we might need to remove space not before the residue name, but before the atomic label:
"HETATM100000C15  ole"
6:11 to "100000"
12:16 to "C15  "
17:20 to "ole"

**Comment by ssmirella** [comment]
Hi Kateryna,

With another test here, I have the impression that the CONNECT fields might be affected as well. Is it possible to get it checked?

Thank you,

Mirella

**Comment by agiliopadua** [comment]
The OpenMM folks have come across this issue of atom numbers > 99999 and provided a solution using hex numbers of even '*****' to comply with vmd.
https://github.com/openmm/openmm/issues/659
https://github.com/openmm/openmm/pull/664
I don't have the time now to look at the details of how to modify fftool. I also don't know if the CONECT really matter.

**Comment by agiliopadua** [comment]
Fixed!
